// renderers/react/src/v0_9/A2uiSurface.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Surface renderer driven by the node layer.
 *
 * `A2uiSurface` constructs one `NodeResolver` and renders the resolved
 * `ComponentNode` tree it maintains. Each node's view subscribes to that
 * node's props signal only, so a data change re-renders exactly the affected
 * component.
 *
 * Views receive props converted to the shapes the view contract uses: child
 * ids as strings, template children as `{id, basePath}` pairs, and
 * `buildChild` maps those refs back to their live nodes. A property is a
 * child reference when the catalog schema declares it as one
 * (`ComponentIdSchema` / `ChildListSchema`, or `componentIdWithDescription` /
 * `childListWithDescription` when adding prose); ids passed to `buildChild`
 * from undeclared properties cannot be resolved.
 */

import React, {memo, useCallback, useMemo, useSyncExternalStore} from 'react';
import {
  ComponentContext,
  ComponentNode,
  NodeResolver,
  effect,
  getValue,
  peekValue,
  type NodeProps,
  type Signal,
  type SurfaceModel,
} from '@a2ui/web_core/v0_9';
import type {ReactComponentImplementation} from './adapter';

function useSignalValue<T>(signal: Signal<T>): T {
  const subscribe = useCallback(
    (onChange: () => void) =>
      effect(() => {
        getValue(signal);
        onChange();
      }),
    [signal],
  );
  const getSnapshot = useCallback(() => peekValue(signal), [signal]);
  return useSyncExternalStore(subscribe, getSnapshot);
}

/** Child nodes of one view, keyed by componentId and by componentId@dataPath. */
type ChildIndex = Map<string, ComponentNode>;

function registerChild(index: ChildIndex, child: ComponentNode): void {
  index.set(`${child.componentId}@${child.dataPath}`, child);
  if (!index.has(child.componentId)) {
    index.set(child.componentId, child);
  }
}

/**
 * Converts node-resolved props to the shapes views are written against: a
 * child node becomes its componentId string when it shares the parent's data
 * scope, and an `{id, basePath}` pair when it was spawned at a scoped path
 * (a template item). The nodes themselves are collected into `index` for
 * `buildChild` to find again.
 */
function toViewValue(parent: ComponentNode, value: unknown, index: ChildIndex): unknown {
  if (value instanceof ComponentNode) {
    registerChild(index, value);
    if (value.dataPath !== parent.dataPath) {
      return {id: value.componentId, basePath: value.dataPath};
    }
    return value.componentId;
  }
  if (Array.isArray(value)) {
    return value.map(item => toViewValue(parent, item, index));
  }
  if (value && typeof value === 'object') {
    const result: Record<string, unknown> = {};
    for (const [key, inner] of Object.entries(value)) {
      result[key] = toViewValue(parent, inner, index);
    }
    return result;
  }
  return value;
}

const NodeView = memo(
  ({surface, node}: {surface: SurfaceModel<ReactComponentImplementation>; node: ComponentNode}) => {
    const resolved = useSignalValue(node.props);

    const {viewProps, childIndex} = useMemo(() => {
      const index: ChildIndex = new Map();
      const converted: NodeProps = {};
      for (const [key, value] of Object.entries(resolved)) {
        converted[key] = toViewValue(node, value, index);
      }
      return {viewProps: converted, childIndex: index};
    }, [node, resolved]);

    const context = useMemo(
      () =>
        node.isPlaceholder
          ? undefined
          : new ComponentContext(surface, node.componentId, node.dataPath),
      [surface, node],
    );

    const buildChild = useCallback(
      (child: string | ComponentNode, basePath?: string): React.ReactNode => {
        const childNode =
          child instanceof ComponentNode
            ? child
            : (childIndex.get(basePath ? `${child}@${basePath}` : child) ??
              childIndex.get(`${child}@${node.dataPath}`));
        if (childNode) {
          return <NodeView key={childNode.instanceId} surface={surface} node={childNode} />;
        }
        return (
          <div key={`${String(child)}`} style={{color: 'gray', padding: '4px'}}>
            [Unresolved child {String(child)}]
          </div>
        );
      },
      [surface, childIndex, node],
    );

    if (node.isPlaceholder) {
      return <div style={{color: 'gray', padding: '4px'}}>[Loading {node.componentId}...]</div>;
    }
    const impl = surface.catalog.components.get(node.type);
    if (!impl) {
      return <div style={{color: 'red'}}>Unknown component: {node.type}</div>;
    }
    const View = impl.view;
    if (!View) {
      const Render = impl.render;
      if (!Render) {
        return <div style={{color: 'red'}}>Unrenderable component: {node.type}</div>;
      }
      // Binderless implementation: renders from the context, binding itself.
      return <Render context={context!} buildChild={buildChild} />;
    }
    return <View props={viewProps} buildChild={buildChild} context={context!} />;
  },
);
NodeView.displayName = 'NodeView';

export const A2uiSurface: React.FC<{
  surface: SurfaceModel<ReactComponentImplementation>;
}> = ({surface}) => {
  // The resolver is created inside subscribe, which React calls only for
  // committed renders: a render that is discarded (concurrent mode,
  // Suspense) never constructs one, and every constructed resolver is
  // disposed by its own unsubscribe. StrictMode's double mount simply
  // creates and disposes two in turn.
  const box = useMemo(
    () => ({resolver: undefined as NodeResolver<ReactComponentImplementation> | undefined}),
    [surface],
  );
  const subscribe = useCallback(
    (onChange: () => void) => {
      const resolver = new NodeResolver(surface, surface.catalog);
      box.resolver = resolver;
      onChange();
      const stopEffect = effect(() => {
        getValue(resolver.rootNode);
        onChange();
      });
      return () => {
        stopEffect();
        resolver.dispose();
        if (box.resolver === resolver) {
          box.resolver = undefined;
        }
      };
    },
    [surface, box],
  );
  const getSnapshot = useCallback(
    () => (box.resolver ? peekValue(box.resolver.rootNode) : undefined),
    [box],
  );
  const root = useSyncExternalStore(subscribe, getSnapshot);

  if (!root) {
    return <div style={{color: 'gray', padding: '4px'}}>[Loading root...]</div>;
  }
  return <NodeView surface={surface} node={root} />;
};

/** @deprecated `A2uiSurface` renders through the node layer; use it directly. */
export const A2uiNodeSurface = A2uiSurface;

// renderers/lit/src/v0_9/surface/a2ui-surface.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, nothing, LitElement, PropertyValues} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {
  ComponentNode,
  NodeResolver,
  SurfaceModel,
  effect,
  getValue,
  peekValue,
} from '@a2ui/web_core/v0_9';
import {renderA2uiNode} from './render-a2ui-node.js';
import {LitComponentApi} from '../types.js';

/**
 * A Lit component that renders an A2UI Surface.
 *
 * This component takes a `SurfaceModel`, resolves it through a
 * `NodeResolver`, and renders the resolved component tree. It handles
 * loading states while the root component is not yet available.
 *
 * @element a2ui-surface
 */
@customElement('a2ui-surface')
export class A2uiSurface extends LitElement {
  /**
   * The surface model containing the component tree and catalog.
   */
  @property({type: Object}) accessor surface: SurfaceModel<LitComponentApi> | undefined;

  private resolver?: NodeResolver<LitComponentApi>;
  private stopEffect?: () => void;
  private lastRoot: ComponentNode | undefined;

  /**
   * Handles lifecycle updates, specifically when the `surface` property changes.
   */
  protected override willUpdate(changedProperties: PropertyValues) {
    if (changedProperties.has('surface')) {
      this.teardown();
      this.setup();
    }
  }

  /**
   * Recreates the resolver when the element reconnects after a disconnect.
   */
  override connectedCallback() {
    super.connectedCallback();
    if (this.surface && !this.resolver) {
      this.setup();
    }
  }

  /**
   * Disposes the resolver and its whole node tree.
   */
  override disconnectedCallback() {
    super.disconnectedCallback();
    this.teardown();
  }

  private setup() {
    if (!this.surface) return;
    const resolver = new NodeResolver(this.surface, this.surface.catalog);
    this.resolver = resolver;
    this.lastRoot = peekValue(resolver.rootNode);
    this.stopEffect = effect(() => {
      const root = getValue(resolver.rootNode);
      // The effect runs synchronously at subscription time; the identity
      // check absorbs that first call.
      if (root !== this.lastRoot) {
        this.lastRoot = root;
        this.requestUpdate();
      }
    });
  }

  private teardown() {
    this.stopEffect?.();
    this.stopEffect = undefined;
    this.resolver?.dispose();
    this.resolver = undefined;
    this.lastRoot = undefined;
  }

  /**
   * Renders the surface.
   *
   * If `surface` is not set, returns `nothing`.
   * If the root component is not yet available, renders a loading state.
   * Otherwise, renders the resolved root node.
   */
  override render() {
    if (!this.surface || !this.resolver) return nothing;
    const root = peekValue(this.resolver.rootNode);
    if (!root) {
      return html`<slot name="loading"><div>Loading surface...</div></slot>`;
    }
    return renderA2uiNode(this.surface, root);
  }
}
